# Generated by Django 4.2.2 on 2023-06-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_department_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jun', 'Junior'), ('mid', 'Middle'), ('sen', 'Senior')], default='jun', max_length=10),
        ),
    ]
